---
satellites_total:
  distribution_type: uniform
  min_val: 8000
  max_val: 42000

bandwidth_per_satellite_mbps:
  distribution_type: normal
  mean: 17
  std: 3

oversubscription_ratio:
  distribution_type: lognormal
  mean: 3.0     # log-space mean
  std: 1.0      # log-space std

minimum_bandwidth_per_user_mbps:
  distribution_type: normal
  mean: 20
  std: 2

gdp_fraction_willingness_to_pay:
  distribution_type: beta
  alpha: 2
  beta: 10
  scale: 0.05   # scale beta(2,10) to max 5% of GDP
